on:
  push:
    branches:
      - master

name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Release drafter
        id: release-drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: auto-release
          IMAGE_TAG: ${{ steps.release-drafter.tag_name }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .